spring:
  datasource:
    url: jdbc:mysql://localhost:3306/faunaworld
    username: root
    password: xhj0816
    driver-class-name: com.mysql.cj.jdbc.Driver

    druid:
      aop-patterns: pers.xinhaojie.admin.*
      filters: wall,stat
      filter:
        stat:
          slow-sql-millis: 1000
          log-slow-sql: true
          enabled: true
        wall:
          enabled: true
          config:
            drop-table-allow: false
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
      stat-view-servlet:
        enabled: true
        login-password: admin
        reset-enable: false
        login-username: admin
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
